Add script to renumber parameter ids
openforcefield/openff-sage pull request #1
Opened 2021-08-11 16:16 UTC by SimonBoothroyd

## Description

This PR adds a new script that will re-number the parameter ids in a force field.

## Examples

```
python ./scripts/renumber-parameters.py -i openff-2.0.0-rc.2.offxml -o openff-2.0.0-rc.3.offxml
python ./scripts/renumber-parameters.py -i openff_unconstrained-2.0.0-rc.2.offxml -o openff_unconstrained-2.0.0-rc.3.offxml
```

## Status

- [X] Ready to go

2021-08-11 17:41 UTC, davidlmobley approved these changes
LGTM! Thanks!

2021-08-12 20:00 UTC, j-wags requested changes
We should output a mapping from the old to new parameter ids - It'll be good to have this lined up for the initial release so the artifacts can be linked together.

2021-08-17 17:14 UTC, SimonBoothroyd commented
@j-wags should be done in a4c2aea

2021-08-18 02:30 UTC, j-wags approved these changes
LGTM. Thanks, Simon!

2021-08-18 02:30 UTC, merged

2021-11-15 18:29 UTC, j-wags commented
@SimonBoothroyd Do you recall if we stored the `id_map.json` artifact anywhere? @ldamore was just looking for it, and I can't find it either. If you still have it handy, could you attach it as an asset to the [`openff-forcefields` 2.0.0 release](https://github.com/openforcefield/openff-forcefields/releases)?

2021-11-15 18:37 UTC, davidlmobley commented
Huh, here's the script, but I thought he'd deposited the file too... https://github.com/openforcefield/openff-sage/blob/main/scripts/renumber-parameters.py

2021-11-15 19:16 UTC, j-wags commented
I can imagine this being a case of Simon asking where the file should go, me saying "oh well there are so many repos with stuff in their git trees, and different stuff in their artifacts, and this is just a metadata update, so let me think about what's the optimal thing to do...", then getting distracted by a fire and never answering him. So there's a good chance it's my fault.

2021-11-29 18:35 UTC, j-wags commented
Ah, Simon indeed HAD sent me this file back in August, and I just never uploaded it. Apologies for losing track of this. I've added the file to the release assets of the openff-forcefields 2.0.0 release.